import type { ModelPricing } from './models.js';

/**
 * GitHub Copilot model pricing. All rates are per 1 million tokens in USD.
 *
 * AUTO-GENERATED by tools/update-pricing/generate.mjs — do not edit by hand.
 * Source: https://github.com/github/docs/blob/main/data/tables/copilot/models-and-pricing.yml
 * To change legacy/extra models, edit tools/update-pricing/extra-models.json.
 */
export const DEFAULT_PRICING: Record<string, ModelPricing> = {
  // OpenAI
  'gpt-5-mini': { input: 0.25, output: 2.00, cached: 0.025 },
  'gpt-5.3-codex': { input: 1.75, output: 14.00, cached: 0.175 },
  'gpt-5.4': { input: 2.50, output: 15.00, cached: 0.25 },
  'gpt-5.4-mini': { input: 0.75, output: 4.50, cached: 0.075 },
  'gpt-5.4-nano': { input: 0.20, output: 1.25, cached: 0.02 },
  'gpt-5.5': { input: 5.00, output: 30.00, cached: 0.50 },

  // Anthropic (includes cache write cost)
  'claude-haiku-4-5': { input: 1.00, output: 5.00, cached: 0.10, cacheWrite: 1.25 },
  'claude-sonnet-4': { input: 3.00, output: 15.00, cached: 0.30, cacheWrite: 3.75 },
  'claude-sonnet-4-5': { input: 3.00, output: 15.00, cached: 0.30, cacheWrite: 3.75 },
  'claude-sonnet-4-6': { input: 3.00, output: 15.00, cached: 0.30, cacheWrite: 3.75 },
  'claude-opus-4-5': { input: 5.00, output: 25.00, cached: 0.50, cacheWrite: 6.25 },
  'claude-opus-4-6': { input: 5.00, output: 25.00, cached: 0.50, cacheWrite: 6.25 },
  'claude-opus-4-7': { input: 5.00, output: 25.00, cached: 0.50, cacheWrite: 6.25 },
  'claude-opus-4-8': { input: 5.00, output: 25.00, cached: 0.50, cacheWrite: 6.25 },
  'claude-sonnet-5': { input: 2.00, output: 10.00, cached: 0.20, cacheWrite: 2.50 },
  'claude-opus-4-8-(fast-mode)-(preview)': { input: 10.00, output: 50.00, cached: 1.00, cacheWrite: 12.50 },
  'claude-fable-5': { input: 10.00, output: 50.00, cached: 1.00, cacheWrite: 12.50 },

  // Google
  'gemini-2.5-pro': { input: 1.25, output: 10.00, cached: 0.125 },
  'gemini-3-flash': { input: 0.50, output: 3.00, cached: 0.05 },
  'gemini-3.1-pro': { input: 2.00, output: 12.00, cached: 0.20 },
  'gemini-3.5-flash': { input: 1.50, output: 9.00, cached: 0.15 },

  // GitHub fine-tuned
  'raptor-mini': { input: 0.25, output: 2.00, cached: 0.025 },

  // microsoft
  'mai-code-1-flash': { input: 0.75, output: 4.50, cached: 0.075 },

  // Additional models not in the official pricing table (see extra-models.json)
  'gpt-4o-mini': { input: 0.15, output: 0.60, cached: 0.075 },
  'gpt-4o': { input: 2.50, output: 10.00, cached: 1.25 },
  'o1': { input: 15.00, output: 60.00, cached: 7.50 },
  'o1-mini': { input: 3.00, output: 12.00, cached: 1.50 },
  'o3-mini': { input: 1.10, output: 4.40, cached: 0.55 },
  'goldeneye': { input: 1.25, output: 10.00, cached: 0.125 },

  // Deprecated models retained for historical telemetry (see extra-models.json)
  'gpt-4.1': { input: 2.00, output: 8.00, cached: 0.50 },
  'gpt-5.2': { input: 1.75, output: 14.00, cached: 0.175 },
  'gpt-5.2-codex': { input: 1.75, output: 14.00, cached: 0.175 },
};
